### ISSUE TITLE
AssertionError("Torch not compiled with CUDA enabled")

### ISSUE THREAD

**Issue by ORENYT** [wang-zidu/3DDFA-V3#11]
Site packages were installed via secondary option (# or: conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=10.2 -c pytorch)
First opion was unavailable due to unexisting version of torch
Platform: Windows 10
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu102 (from versions: 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.8.1+cu102, 1.9.0, 1.9.0+cu102,
 1.9.1, 1.9.1+cu102, 1.10.0, 1.10.0+cu102, 1.10.1, 1.10.1+cu102, 1.10.2, 1.10.2+cu102, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1)

When I tried to use secondary option, I've got an error due to unexisting cuda:
(TDDFAV3) PS C:\Users\oreny\PycharmProjects\3DDFA-V3\3DDFA-V3> python demo.py --inputpath examples/ --savepath examples/results --device cuda --iscrop 1 --detector retinaface --ldm68 1 --ldm106 1 --ldm106_2d 1 --ldm134 1 --seg_visible 1 --seg 1 --useTex 1 --extractTex 1 --backbone resnet50
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
Traceback (most recent call last):
  File "demo.py", line 77, in <module>
    main(parser.parse_args())
  File "demo.py", line 15, in main
    recon_model = face_model(args)
  File "C:\Users\oreny\PycharmProjects\3DDFA-V3\3DDFA-V3\model\recon.py", line 78, in __init__
    self.u = torch.tensor(model['u'], requires_grad=False, dtype=torch.float32, device=self.device)
  File "C:\Users\oreny\miniconda3\envs\TDDFAV3\lib\site-packages\torch\cuda\__init__.py", line 211, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Any ideas how to fix it?

**Comment by wang-zidu** [comment]
Thank you for your feedback! In our tests, there wasn't a strict restriction on the version of PyTorch, but my environment is Ubuntu. I believe the issue might be caused by the Windows system. I will try to resolve this issue (possibly by switching to an easier renderer, supporting CPU, etc.) in the next few days (I will try to complete it within a week) and will inform you immediately once there is an update. If you are eager to see the results, I suggest using an Ubuntu system or trying more different versions of PyTorch.

**Comment by wang-zidu** [comment]
Thank you for your support and patience. We have now updated a new fast CPU renderer that can be used as an alternative to nvdiffrast in environments where configuring nvdiffrast is difficult. You can use `--device cpu` to invoke this new CPU renderer. If you still need to ensure that network inference runs on the GPU, you may need to make some additional modifications in [model/recon.py](https://github.com/wang-zidu/3DDFA-V3/blob/main/model/recon.py) (simply replace nvdiffrast with the new renderer when running with `--device cuda`). Additionally, I successfully ran this project on my laptop (Windows 10) using PyTorch 1.10.
